module.exports = {
 'A' :   95, //Villers Clairlieu - CES Chepfer - Laxou Provinces / Villers Lycée Stanislas',
 'B' :   96, //Malzéville Le Nid / C.E.S Paul Verlaine - C.E.S Nicklès',
 'C' :   97, //Jarville Léon Songeur - Heillecourt Husson / CES Montaigu',
 'D' :   98, //L\'Orée du Bois / C.E.S Monod',
 'E' :   99, //Houdemont Les Egrez / Vandoeuvre Monplaisir - Villers G. Chepfer',
 'F' :   100, //Saulxures / Lycée Varoquaux',
 'G' :   101, //Art-sur-Meurthe / Lycée Varoquaux',
 'H' :   102, //Nancy Centre des Congrès / Art-sur-Meurthe Bosserville',
 'J' :   104, //Nancy Centre des Congrès / Malzéville Pixérécourt',
 'K' :   105, //Nancy Centre des Congrès / Lycée Varoquaux',
 'M' :   107, //Fléville / Jarville Sion',
 'N' :   108, //CEPAL',
 'S' :   120, //Fléville / Villers Lycée Stanislas',
 '1' :   81, //Vandoeuvre CHU Brabois / Essey Mouzimpré',
 '2' :   82, //Laxou Plateau de Haye / Laneuveville Centre',
 '3' :   83, //Laxou Provinces / Seichamps Haie Cerlin',
 '4' :   84, //Laxou Champ le Boeuf / Vandoeuvre Roberval',
 '5' :   85, //Laxou Champ le Boeuf / Seichamps Voirincourt',
 '6' :   86, //Villers Clairlieu / Malzéville Savlons',
 '7' :   22, //Houdemont Porte sud / Dommartemont',
 '8' :   8, //Vandoeuvre CHU / Malzéville - Malzéville Pixerécourt',
 '9' :   87, //Nancy Tamaris / Saulxures',
 '10' :   21, //Nancy Pôle de santé - Jarville Sion',
 '11' :   88, //Nancy Centre de Congrès Prouvé / Fléville - Fléville Dynapôle',
 '12' :   89, //Nancy Centre de Congrès Prouvé / Heillecourt',
 '13' :   90, //Nancy Centre de Congrès Prouvé / Art-sur-Meurthe',
 '14' :   6, //Nancy Centre de Congrès Prouvé / Ludres',
 '15' :   16, //Laneuveville Gare / Villers Lycée Stanislas',
 '16' :   5, //Villers-Clairlieu / Malzéville Savlons',
 '17' :   115, //Ludres / Villers Lycée Stanislas',
 '18' :   116, //Pulnoy / Gérard Barrois Stade Marcel Picot - Dommartemont',
 '19' :   117, //Jarville Gabriel Fauré / Maxéville Mairie',
 'Mobistan Est' :   91, //Gérard Barrois - Stade Marcel Picot / Essey Emile Gallé',
 'Mobistan Ouest' :   92, //Vandoeuvre Faculté de médecine / Vandoeuvre Remich',
 'Ptit Stan Laxou' :   93, //Laxou CPN - Laxou Provinces / Laxou Sapinière',
 'Ptit Stan de Pulnoy' :   118, //SEICHAMPS Montréal / Essey Mouzimpré',
 'Ptit Stan de Nancy' :   119, //Malzéville Mairie / Nancy Cimetière du Sud',
};
